In [24]:
import numpy as np

import pandas as pd

In [25]:
cars_new = pd.read_csv('cars_null.csv')

In [26]:
cars_new.head()

,Model,MPG,Cylinders,DISP,HP,D_Ratio,Weight,QSEC,VS,AM,Gear,Carb
0,Mazda RX4,21.0,6,160.0,110.0,3.90,2.620,16.46,0,1,4.0,4.0
1,Mazda RX4 Wag,21.0,6,160.0,110.0,3.90,2.875,17.02,0,1,4.0,4.0
2,Datsun 710,22.8,4,108.0,93.0,3.85,2.320,18.61,1,1,4.0,1.0
3,Hornet 4 Drive,21.4,6,258.0,110.0,3.08,3.215,19.44,1,0,3.0,1.0
4,Hornet Sportabout,18.7,8,360.0,175.0,3.15,3.440,17.02,0,0,3.0,2.0

In [4]:
cars_new.tail()

,Model,MPG,Cylinders,DISP,HP,D_Ratio,Weight,QSEC,VS,AM,Gear,Carb
27,Lotus Europa,30.4,4,95.1,113.0,3.77,1.513,16.9,1,1,5.0,2.0
28,Ford Pantera L,15.8,8,351.0,264.0,4.22,3.170,14.5,0,1,5.0,4.0
29,Ferrari Dino,19.7,6,145.0,175.0,3.62,2.770,15.5,0,1,5.0,6.0
30,Maserati Bora,15.0,8,301.0,335.0,3.54,3.570,14.6,0,1,5.0,8.0
31,Volvo 142E,21.4,4,121.0,109.0,4.11,2.780,18.6,1,1,4.0,2.0

In [5]:
cars_new

,Model,MPG,Cylinders,DISP,HP,D_Ratio,Weight,QSEC,VS,AM,Gear,Carb
0,Mazda RX4,21.0,6,160.0,110.0,3.90,2.620,16.46,0,1,4.0,4.0
1,Mazda RX4 Wag,21.0,6,160.0,110.0,3.90,2.875,17.02,0,1,4.0,4.0
2,Datsun 710,22.8,4,108.0,93.0,3.85,2.320,18.61,1,1,4.0,1.0
3,Hornet 4 Drive,21.4,6,258.0,110.0,3.08,3.215,19.44,1,0,3.0,1.0
4,Hornet Sportabout,18.7,8,360.0,175.0,3.15,3.440,17.02,0,0,3.0,2.0
5,Valiant,18.1,6,225.0,105.0,2.76,3.460,20.22,1,0,3.0,1.0
6,Duster 360,14.3,8,360.0,245.0,3.21,3.570,15.84,0,0,3.0,4.0
7,Merc 240D,24.4,4,146.7,62.0,3.69,3.190,20.00,1,0,4.0,2.0
8,Merc 230,22.8,4,140.8,95.0,3.92,3.150,22.90,1,0,4.0,2.0
9,Merc 280,19.2,6,167.6,123.0,3.92,3.440,18.30,1,0,4.0,4.0
10,Merc 280C,17.8,6,167.6,123.0,3.92,3.440,18.90,1,0,4.0,4.0
11,Merc 450SE,16.4,8,275.8,180.0,3.07,4.070,17.40,0,0,3.0,3.0
12,Merc 450SL,17.3,8,NaN,180.0,3.07,3.730,17.60,0,0,3.0,3.0
13,Merc 450SLC,15.2,8,NaN,180.0,3.07,3.780,18.00,0,0,3.0,3.0
14,Cadillac Fleetwood,10.4,8,472.0,205.0,2.93,5.250,17.98,0,0,NaN,4.0
15,Lincoln Continental,NaN,8,460.0,215.0,NaN,5.424,17.82,0,0,3.0,4.0
16,Chrysler Imperial,14.7,8,440.0,230.0,3.23,5.345,NaN,0,0,3.0,4.0
17,Fiat 128,32.4,4,78.7,66.0,4.08,2.200,19.47,1,1,4.0,1.0
18,Honda Civic,30.4,4,75.7,52.0,4.93,1.615,18.52,1,1,4.0,NaN
19,Toyota Corolla,33.9,4,71.1,65.0,4.22,1.835,19.90,1,1,4.0,1.0
20,Toyota Corona,21.5,4,120.1,97.0,3.70,2.465,20.01,1,0,3.0,1.0
21,Dodge Challenger,15.5,8,318.0,150.0,2.76,3.520,16.87,0,0,3.0,2.0
22,AMC Javelin,15.2,8,304.0,NaN,3.15,3.435,17.30,0,0,3.0,2.0
23,Camaro Z28,13.3,8,350.0,245.0,3.73,3.840,15.41,0,0,3.0,4.0
24,Pontiac Firebird,19.2,8,400.0,175.0,3.08,3.845,17.05,0,0,3.0,2.0
25,Fiat X1-9,27.3,4,79.0,66.0,4.08,1.935,18.90,1,1,4.0,1.0
26,Porsche 914-2,26.0,4,120.3,91.0,4.43,NaN,16.70,0,1,5.0,2.0
27,Lotus Europa,30.4,4,95.1,113.0,3.77,1.513,16.90,1,1,5.0,2.0
28,Ford Pantera L,15.8,8,351.0,264.0,4.22,3.170,14.50,0,1,5.0,4.0
29,Ferrari Dino,19.7,6,145.0,175.0,3.62,2.770,15.50,0,1,5.0,6.0
30,Maserati Bora,15.0,8,301.0,335.0,3.54,3.570,14.60,0,1,5.0,8.0
31,Volvo 142E,21.4,4,121.0,109.0,4.11,2.780,18.60,1,1,4.0,2.0

In [6]:
cars_new.isnull()

,Model,MPG,Cylinders,DISP,HP,D_Ratio,Weight,QSEC,VS,AM,Gear,Carb
0,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False,False,False,False,False
10,False,False,False,False,False,False,False,False,False,False,False,False
11,False,False,False,False,False,False,False,False,False,False,False,False
12,False,False,False,True,False,False,False,False,False,False,False,False
13,False,False,False,True,False,False,False,False,False,False,False,False
14,False,False,False,False,False,False,False,False,False,False,True,False
15,False,True,False,False,False,True,False,False,False,False,False,False
16,False,False,False,False,False,False,False,True,False,False,False,False
17,False,False,False,False,False,False,False,False,False,False,False,False
18,False,False,False,False,False,False,False,False,False,False,False,True
19,False,False,False,False,False,False,False,False,False,False,False,False
20,False,False,False,False,False,False,False,False,False,False,False,False
21,False,False,False,False,False,False,False,False,False,False,False,False
22,False,False,False,False,True,False,False,False,False,False,False,False
23,False,False,False,False,False,False,False,False,False,False,False,False
24,False,False,False,False,False,False,False,False,False,False,False,False
25,False,False,False,False,False,False,False,False,False,False,False,False
26,False,False,False,False,False,False,True,False,False,False,False,False
27,False,False,False,False,False,False,False,False,False,False,False,False
28,False,False,False,False,False,False,False,False,False,False,False,False
29,False,False,False,False,False,False,False,False,False,False,False,False
30,False,False,False,False,False,False,False,False,False,False,False,False
31,False,False,False,False,False,False,False,False,False,False,False,False

In [8]:
cars_new.isnull().sum()

Model        0
MPG          1
Cylinders    0
DISP         2
HP           1
D_Ratio      1
Weight       1
QSEC         1
VS           0
AM           0
Gear         1
Carb         1
dtype: int64

In [9]:
cars_new.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 12 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Model      32 non-null     object
 1   MPG        31 non-null     float64
 2   Cylinders  32 non-null     int64
 3   DISP       30 non-null     float64
 4   HP         31 non-null     float64
 5   D_Ratio    31 non-null     float64
 6   Weight     31 non-null     float64
 7   QSEC       31 non-null     float64
 8   VS         32 non-null     int64
 9   AM         32 non-null     int64
 10  Gear       31 non-null     float64
 11  Carb       31 non-null     float64
dtypes: float64(8), int64(3), object(1)
memory usage: 3.1+ KB

In [13]:
cars_new['Model'].isnull().sum()

0

In [18]:
cars_new[['Model','MPG']].isnull().sum()

Model    0
MPG      1
dtype: int64

In [19]:
cars_new.dropna() #  Row Operation

,Model,MPG,Cylinders,DISP,HP,D_Ratio,Weight,QSEC,VS,AM,Gear,Carb
0,Mazda RX4,21.0,6,160.0,110.0,3.90,2.620,16.46,0,1,4.0,4.0
1,Mazda RX4 Wag,21.0,6,160.0,110.0,3.90,2.875,17.02,0,1,4.0,4.0
2,Datsun 710,22.8,4,108.0,93.0,3.85,2.320,18.61,1,1,4.0,1.0
3,Hornet 4 Drive,21.4,6,258.0,110.0,3.08,3.215,19.44,1,0,3.0,1.0
4,Hornet Sportabout,18.7,8,360.0,175.0,3.15,3.440,17.02,0,0,3.0,2.0
5,Valiant,18.1,6,225.0,105.0,2.76,3.460,20.22,1,0,3.0,1.0
6,Duster 360,14.3,8,360.0,245.0,3.21,3.570,15.84,0,0,3.0,4.0
7,Merc 240D,24.4,4,146.7,62.0,3.69,3.190,20.00,1,0,4.0,2.0
8,Merc 230,22.8,4,140.8,95.0,3.92,3.150,22.90,1,0,4.0,2.0
9,Merc 280,19.2,6,167.6,123.0,3.92,3.440,18.30,1,0,4.0,4.0
10,Merc 280C,17.8,6,167.6,123.0,3.92,3.440,18.90,1,0,4.0,4.0
11,Merc 450SE,16.4,8,275.8,180.0,3.07,4.070,17.40,0,0,3.0,3.0
17,Fiat 128,32.4,4,78.7,66.0,4.08,2.200,19.47,1,1,4.0,1.0
19,Toyota Corolla,33.9,4,71.1,65.0,4.22,1.835,19.90,1,1,4.0,1.0
20,Toyota Corona,21.5,4,120.1,97.0,3.70,2.465,20.01,1,0,3.0,1.0
21,Dodge Challenger,15.5,8,318.0,150.0,2.76,3.520,16.87,0,0,3.0,2.0
23,Camaro Z28,13.3,8,350.0,245.0,3.73,3.840,15.41,0,0,3.0,4.0
24,Pontiac Firebird,19.2,8,400.0,175.0,3.08,3.845,17.05,0,0,3.0,2.0
25,Fiat X1-9,27.3,4,79.0,66.0,4.08,1.935,18.90,1,1,4.0,1.0
27,Lotus Europa,30.4,4,95.1,113.0,3.77,1.513,16.90,1,1,5.0,2.0
28,Ford Pantera L,15.8,8,351.0,264.0,4.22,3.170,14.50,0,1,5.0,4.0
29,Ferrari Dino,19.7,6,145.0,175.0,3.62,2.770,15.50,0,1,5.0,6.0
30,Maserati Bora,15.0,8,301.0,335.0,3.54,3.570,14.60,0,1,5.0,8.0
31,Volvo 142E,21.4,4,121.0,109.0,4.11,2.780,18.60,1,1,4.0,2.0

In [22]:
# Columns Opeartion

#Inplace = False ( Default Value)
# inplace  = True

cars_new.dropna(axis = 1),# inplace=True)

In [27]:
cars_new

,Model,MPG,Cylinders,DISP,HP,D_Ratio,Weight,QSEC,VS,AM,Gear,Carb
0,Mazda RX4,21.0,6,160.0,110.0,3.90,2.620,16.46,0,1,4.0,4.0
1,Mazda RX4 Wag,21.0,6,160.0,110.0,3.90,2.875,17.02,0,1,4.0,4.0
2,Datsun 710,22.8,4,108.0,93.0,3.85,2.320,18.61,1,1,4.0,1.0
3,Hornet 4 Drive,21.4,6,258.0,110.0,3.08,3.215,19.44,1,0,3.0,1.0
4,Hornet Sportabout,18.7,8,360.0,175.0,3.15,3.440,17.02,0,0,3.0,2.0
5,Valiant,18.1,6,225.0,105.0,2.76,3.460,20.22,1,0,3.0,1.0
6,Duster 360,14.3,8,360.0,245.0,3.21,3.570,15.84,0,0,3.0,4.0
7,Merc 240D,24.4,4,146.7,62.0,3.69,3.190,20.00,1,0,4.0,2.0
8,Merc 230,22.8,4,140.8,95.0,3.92,3.150,22.90,1,0,4.0,2.0
9,Merc 280,19.2,6,167.6,123.0,3.92,3.440,18.30,1,0,4.0,4.0
10,Merc 280C,17.8,6,167.6,123.0,3.92,3.440,18.90,1,0,4.0,4.0
11,Merc 450SE,16.4,8,275.8,180.0,3.07,4.070,17.40,0,0,3.0,3.0
12,Merc 450SL,17.3,8,NaN,180.0,3.07,3.730,17.60,0,0,3.0,3.0
13,Merc 450SLC,15.2,8,NaN,180.0,3.07,3.780,18.00,0,0,3.0,3.0
14,Cadillac Fleetwood,10.4,8,472.0,205.0,2.93,5.250,17.98,0,0,NaN,4.0
15,Lincoln Continental,NaN,8,460.0,215.0,NaN,5.424,17.82,0,0,3.0,4.0
16,Chrysler Imperial,14.7,8,440.0,230.0,3.23,5.345,NaN,0,0,3.0,4.0
17,Fiat 128,32.4,4,78.7,66.0,4.08,2.200,19.47,1,1,4.0,1.0
18,Honda Civic,30.4,4,75.7,52.0,4.93,1.615,18.52,1,1,4.0,NaN
19,Toyota Corolla,33.9,4,71.1,65.0,4.22,1.835,19.90,1,1,4.0,1.0
20,Toyota Corona,21.5,4,120.1,97.0,3.70,2.465,20.01,1,0,3.0,1.0
21,Dodge Challenger,15.5,8,318.0,150.0,2.76,3.520,16.87,0,0,3.0,2.0
22,AMC Javelin,15.2,8,304.0,NaN,3.15,3.435,17.30,0,0,3.0,2.0
23,Camaro Z28,13.3,8,350.0,245.0,3.73,3.840,15.41,0,0,3.0,4.0
24,Pontiac Firebird,19.2,8,400.0,175.0,3.08,3.845,17.05,0,0,3.0,2.0
25,Fiat X1-9,27.3,4,79.0,66.0,4.08,1.935,18.90,1,1,4.0,1.0
26,Porsche 914-2,26.0,4,120.3,91.0,4.43,NaN,16.70,0,1,5.0,2.0
27,Lotus Europa,30.4,4,95.1,113.0,3.77,1.513,16.90,1,1,5.0,2.0
28,Ford Pantera L,15.8,8,351.0,264.0,4.22,3.170,14.50,0,1,5.0,4.0
29,Ferrari Dino,19.7,6,145.0,175.0,3.62,2.770,15.50,0,1,5.0,6.0
30,Maserati Bora,15.0,8,301.0,335.0,3.54,3.570,14.60,0,1,5.0,8.0
31,Volvo 142E,21.4,4,121.0,109.0,4.11,2.780,18.60,1,1,4.0,2.0

In [28]:
cars_new.fillna(value = 999) # Inplace = False ( Default) || True _ Permanent Change

,Model,MPG,Cylinders,DISP,HP,D_Ratio,Weight,QSEC,VS,AM,Gear,Carb
0,Mazda RX4,21.0,6,160.0,110.0,3.90,2.620,16.46,0,1,4.0,4.0
1,Mazda RX4 Wag,21.0,6,160.0,110.0,3.90,2.875,17.02,0,1,4.0,4.0
2,Datsun 710,22.8,4,108.0,93.0,3.85,2.320,18.61,1,1,4.0,1.0
3,Hornet 4 Drive,21.4,6,258.0,110.0,3.08,3.215,19.44,1,0,3.0,1.0
4,Hornet Sportabout,18.7,8,360.0,175.0,3.15,3.440,17.02,0,0,3.0,2.0
5,Valiant,18.1,6,225.0,105.0,2.76,3.460,20.22,1,0,3.0,1.0
6,Duster 360,14.3,8,360.0,245.0,3.21,3.570,15.84,0,0,3.0,4.0
7,Merc 240D,24.4,4,146.7,62.0,3.69,3.190,20.00,1,0,4.0,2.0
8,Merc 230,22.8,4,140.8,95.0,3.92,3.150,22.90,1,0,4.0,2.0
9,Merc 280,19.2,6,167.6,123.0,3.92,3.440,18.30,1,0,4.0,4.0
10,Merc 280C,17.8,6,167.6,123.0,3.92,3.440,18.90,1,0,4.0,4.0
11,Merc 450SE,16.4,8,275.8,180.0,3.07,4.070,17.40,0,0,3.0,3.0
12,Merc 450SL,17.3,8,999.0,180.0,3.07,3.730,17.60,0,0,3.0,3.0
13,Merc 450SLC,15.2,8,999.0,180.0,3.07,3.780,18.00,0,0,3.0,3.0
14,Cadillac Fleetwood,10.4,8,472.0,205.0,2.93,5.250,17.98,0,0,999.0,4.0
15,Lincoln Continental,999.0,8,460.0,215.0,999.00,5.424,17.82,0,0,3.0,4.0
16,Chrysler Imperial,14.7,8,440.0,230.0,3.23,5.345,999.00,0,0,3.0,4.0
17,Fiat 128,32.4,4,78.7,66.0,4.08,2.200,19.47,1,1,4.0,1.0
18,Honda Civic,30.4,4,75.7,52.0,4.93,1.615,18.52,1,1,4.0,999.0
19,Toyota Corolla,33.9,4,71.1,65.0,4.22,1.835,19.90,1,1,4.0,1.0
20,Toyota Corona,21.5,4,120.1,97.0,3.70,2.465,20.01,1,0,3.0,1.0
21,Dodge Challenger,15.5,8,318.0,150.0,2.76,3.520,16.87,0,0,3.0,2.0
22,AMC Javelin,15.2,8,304.0,999.0,3.15,3.435,17.30,0,0,3.0,2.0
23,Camaro Z28,13.3,8,350.0,245.0,3.73,3.840,15.41,0,0,3.0,4.0
24,Pontiac Firebird,19.2,8,400.0,175.0,3.08,3.845,17.05,0,0,3.0,2.0
25,Fiat X1-9,27.3,4,79.0,66.0,4.08,1.935,18.90,1,1,4.0,1.0
26,Porsche 914-2,26.0,4,120.3,91.0,4.43,999.000,16.70,0,1,5.0,2.0
27,Lotus Europa,30.4,4,95.1,113.0,3.77,1.513,16.90,1,1,5.0,2.0
28,Ford Pantera L,15.8,8,351.0,264.0,4.22,3.170,14.50,0,1,5.0,4.0
29,Ferrari Dino,19.7,6,145.0,175.0,3.62,2.770,15.50,0,1,5.0,6.0
30,Maserati Bora,15.0,8,301.0,335.0,3.54,3.570,14.60,0,1,5.0,8.0
31,Volvo 142E,21.4,4,121.0,109.0,4.11,2.780,18.60,1,1,4.0,2.0

In [29]:
cars_new

,Model,MPG,Cylinders,DISP,HP,D_Ratio,Weight,QSEC,VS,AM,Gear,Carb
0,Mazda RX4,21.0,6,160.0,110.0,3.90,2.620,16.46,0,1,4.0,4.0
1,Mazda RX4 Wag,21.0,6,160.0,110.0,3.90,2.875,17.02,0,1,4.0,4.0
2,Datsun 710,22.8,4,108.0,93.0,3.85,2.320,18.61,1,1,4.0,1.0
3,Hornet 4 Drive,21.4,6,258.0,110.0,3.08,3.215,19.44,1,0,3.0,1.0
4,Hornet Sportabout,18.7,8,360.0,175.0,3.15,3.440,17.02,0,0,3.0,2.0
5,Valiant,18.1,6,225.0,105.0,2.76,3.460,20.22,1,0,3.0,1.0
6,Duster 360,14.3,8,360.0,245.0,3.21,3.570,15.84,0,0,3.0,4.0
7,Merc 240D,24.4,4,146.7,62.0,3.69,3.190,20.00,1,0,4.0,2.0
8,Merc 230,22.8,4,140.8,95.0,3.92,3.150,22.90,1,0,4.0,2.0
9,Merc 280,19.2,6,167.6,123.0,3.92,3.440,18.30,1,0,4.0,4.0
10,Merc 280C,17.8,6,167.6,123.0,3.92,3.440,18.90,1,0,4.0,4.0
11,Merc 450SE,16.4,8,275.8,180.0,3.07,4.070,17.40,0,0,3.0,3.0
12,Merc 450SL,17.3,8,NaN,180.0,3.07,3.730,17.60,0,0,3.0,3.0
13,Merc 450SLC,15.2,8,NaN,180.0,3.07,3.780,18.00,0,0,3.0,3.0
14,Cadillac Fleetwood,10.4,8,472.0,205.0,2.93,5.250,17.98,0,0,NaN,4.0
15,Lincoln Continental,NaN,8,460.0,215.0,NaN,5.424,17.82,0,0,3.0,4.0
16,Chrysler Imperial,14.7,8,440.0,230.0,3.23,5.345,NaN,0,0,3.0,4.0
17,Fiat 128,32.4,4,78.7,66.0,4.08,2.200,19.47,1,1,4.0,1.0
18,Honda Civic,30.4,4,75.7,52.0,4.93,1.615,18.52,1,1,4.0,NaN
19,Toyota Corolla,33.9,4,71.1,65.0,4.22,1.835,19.90,1,1,4.0,1.0
20,Toyota Corona,21.5,4,120.1,97.0,3.70,2.465,20.01,1,0,3.0,1.0
21,Dodge Challenger,15.5,8,318.0,150.0,2.76,3.520,16.87,0,0,3.0,2.0
22,AMC Javelin,15.2,8,304.0,NaN,3.15,3.435,17.30,0,0,3.0,2.0
23,Camaro Z28,13.3,8,350.0,245.0,3.73,3.840,15.41,0,0,3.0,4.0
24,Pontiac Firebird,19.2,8,400.0,175.0,3.08,3.845,17.05,0,0,3.0,2.0
25,Fiat X1-9,27.3,4,79.0,66.0,4.08,1.935,18.90,1,1,4.0,1.0
26,Porsche 914-2,26.0,4,120.3,91.0,4.43,NaN,16.70,0,1,5.0,2.0
27,Lotus Europa,30.4,4,95.1,113.0,3.77,1.513,16.90,1,1,5.0,2.0
28,Ford Pantera L,15.8,8,351.0,264.0,4.22,3.170,14.50,0,1,5.0,4.0
29,Ferrari Dino,19.7,6,145.0,175.0,3.62,2.770,15.50,0,1,5.0,6.0
30,Maserati Bora,15.0,8,301.0,335.0,3.54,3.570,14.60,0,1,5.0,8.0
31,Volvo 142E,21.4,4,121.0,109.0,4.11,2.780,18.60,1,1,4.0,2.0

In [30]:
cars_new.fillna(value = 'DATA')

,Model,MPG,Cylinders,DISP,HP,D_Ratio,Weight,QSEC,VS,AM,Gear,Carb
0,Mazda RX4,21.0,6,160.0,110.0,3.9,2.62,16.46,0,1,4.0,4.0
1,Mazda RX4 Wag,21.0,6,160.0,110.0,3.9,2.875,17.02,0,1,4.0,4.0
2,Datsun 710,22.8,4,108.0,93.0,3.85,2.32,18.61,1,1,4.0,1.0
3,Hornet 4 Drive,21.4,6,258.0,110.0,3.08,3.215,19.44,1,0,3.0,1.0
4,Hornet Sportabout,18.7,8,360.0,175.0,3.15,3.44,17.02,0,0,3.0,2.0
5,Valiant,18.1,6,225.0,105.0,2.76,3.46,20.22,1,0,3.0,1.0
6,Duster 360,14.3,8,360.0,245.0,3.21,3.57,15.84,0,0,3.0,4.0
7,Merc 240D,24.4,4,146.7,62.0,3.69,3.19,20.0,1,0,4.0,2.0
8,Merc 230,22.8,4,140.8,95.0,3.92,3.15,22.9,1,0,4.0,2.0
9,Merc 280,19.2,6,167.6,123.0,3.92,3.44,18.3,1,0,4.0,4.0
10,Merc 280C,17.8,6,167.6,123.0,3.92,3.44,18.9,1,0,4.0,4.0
11,Merc 450SE,16.4,8,275.8,180.0,3.07,4.07,17.4,0,0,3.0,3.0
12,Merc 450SL,17.3,8,DATA,180.0,3.07,3.73,17.6,0,0,3.0,3.0
13,Merc 450SLC,15.2,8,DATA,180.0,3.07,3.78,18.0,0,0,3.0,3.0
14,Cadillac Fleetwood,10.4,8,472.0,205.0,2.93,5.25,17.98,0,0,DATA,4.0
15,Lincoln Continental,DATA,8,460.0,215.0,DATA,5.424,17.82,0,0,3.0,4.0
16,Chrysler Imperial,14.7,8,440.0,230.0,3.23,5.345,DATA,0,0,3.0,4.0
17,Fiat 128,32.4,4,78.7,66.0,4.08,2.2,19.47,1,1,4.0,1.0
18,Honda Civic,30.4,4,75.7,52.0,4.93,1.615,18.52,1,1,4.0,DATA
19,Toyota Corolla,33.9,4,71.1,65.0,4.22,1.835,19.9,1,1,4.0,1.0
20,Toyota Corona,21.5,4,120.1,97.0,3.7,2.465,20.01,1,0,3.0,1.0
21,Dodge Challenger,15.5,8,318.0,150.0,2.76,3.52,16.87,0,0,3.0,2.0
22,AMC Javelin,15.2,8,304.0,DATA,3.15,3.435,17.3,0,0,3.0,2.0
23,Camaro Z28,13.3,8,350.0,245.0,3.73,3.84,15.41,0,0,3.0,4.0
24,Pontiac Firebird,19.2,8,400.0,175.0,3.08,3.845,17.05,0,0,3.0,2.0
25,Fiat X1-9,27.3,4,79.0,66.0,4.08,1.935,18.9,1,1,4.0,1.0
26,Porsche 914-2,26.0,4,120.3,91.0,4.43,DATA,16.7,0,1,5.0,2.0
27,Lotus Europa,30.4,4,95.1,113.0,3.77,1.513,16.9,1,1,5.0,2.0
28,Ford Pantera L,15.8,8,351.0,264.0,4.22,3.17,14.5,0,1,5.0,4.0
29,Ferrari Dino,19.7,6,145.0,175.0,3.62,2.77,15.5,0,1,5.0,6.0
30,Maserati Bora,15.0,8,301.0,335.0,3.54,3.57,14.6,0,1,5.0,8.0
31,Volvo 142E,21.4,4,121.0,109.0,4.11,2.78,18.6,1,1,4.0,2.0

In [31]:
x = cars_new["MPG"].mean()

20.40322580645161

In [ ]:
cars_new["Gear"].fillna(value = cars_new["Gear"].mode() )

In [ ]:
cars_new["MPG"].fillna(value = cars_new["MPG"].median() )

In [32]:
cars_new["MPG"].fillna(value = cars_new["MPG"].mean() )

0     21.000000
1     21.000000
2     22.800000
3     21.400000
4     18.700000
5     18.100000
6     14.300000
7     24.400000
8     22.800000
9     19.200000
10    17.800000
11    16.400000
12    17.300000
13    15.200000
14    10.400000
15    20.403226
16    14.700000
17    32.400000
18    30.400000
19    33.900000
20    21.500000
21    15.500000
22    15.200000
23    13.300000
24    19.200000
25    27.300000
26    26.000000
27    30.400000
28    15.800000
29    19.700000
30    15.000000
31    21.400000
Name: MPG, dtype: float64

In [33]:
cars_new

,Model,MPG,Cylinders,DISP,HP,D_Ratio,Weight,QSEC,VS,AM,Gear,Carb
0,Mazda RX4,21.0,6,160.0,110.0,3.90,2.620,16.46,0,1,4.0,4.0
1,Mazda RX4 Wag,21.0,6,160.0,110.0,3.90,2.875,17.02,0,1,4.0,4.0
2,Datsun 710,22.8,4,108.0,93.0,3.85,2.320,18.61,1,1,4.0,1.0
3,Hornet 4 Drive,21.4,6,258.0,110.0,3.08,3.215,19.44,1,0,3.0,1.0
4,Hornet Sportabout,18.7,8,360.0,175.0,3.15,3.440,17.02,0,0,3.0,2.0
5,Valiant,18.1,6,225.0,105.0,2.76,3.460,20.22,1,0,3.0,1.0
6,Duster 360,14.3,8,360.0,245.0,3.21,3.570,15.84,0,0,3.0,4.0
7,Merc 240D,24.4,4,146.7,62.0,3.69,3.190,20.00,1,0,4.0,2.0
8,Merc 230,22.8,4,140.8,95.0,3.92,3.150,22.90,1,0,4.0,2.0
9,Merc 280,19.2,6,167.6,123.0,3.92,3.440,18.30,1,0,4.0,4.0
10,Merc 280C,17.8,6,167.6,123.0,3.92,3.440,18.90,1,0,4.0,4.0
11,Merc 450SE,16.4,8,275.8,180.0,3.07,4.070,17.40,0,0,3.0,3.0
12,Merc 450SL,17.3,8,NaN,180.0,3.07,3.730,17.60,0,0,3.0,3.0
13,Merc 450SLC,15.2,8,NaN,180.0,3.07,3.780,18.00,0,0,3.0,3.0
14,Cadillac Fleetwood,10.4,8,472.0,205.0,2.93,5.250,17.98,0,0,NaN,4.0
15,Lincoln Continental,NaN,8,460.0,215.0,NaN,5.424,17.82,0,0,3.0,4.0
16,Chrysler Imperial,14.7,8,440.0,230.0,3.23,5.345,NaN,0,0,3.0,4.0
17,Fiat 128,32.4,4,78.7,66.0,4.08,2.200,19.47,1,1,4.0,1.0
18,Honda Civic,30.4,4,75.7,52.0,4.93,1.615,18.52,1,1,4.0,NaN
19,Toyota Corolla,33.9,4,71.1,65.0,4.22,1.835,19.90,1,1,4.0,1.0
20,Toyota Corona,21.5,4,120.1,97.0,3.70,2.465,20.01,1,0,3.0,1.0
21,Dodge Challenger,15.5,8,318.0,150.0,2.76,3.520,16.87,0,0,3.0,2.0
22,AMC Javelin,15.2,8,304.0,NaN,3.15,3.435,17.30,0,0,3.0,2.0
23,Camaro Z28,13.3,8,350.0,245.0,3.73,3.840,15.41,0,0,3.0,4.0
24,Pontiac Firebird,19.2,8,400.0,175.0,3.08,3.845,17.05,0,0,3.0,2.0
25,Fiat X1-9,27.3,4,79.0,66.0,4.08,1.935,18.90,1,1,4.0,1.0
26,Porsche 914-2,26.0,4,120.3,91.0,4.43,NaN,16.70,0,1,5.0,2.0
27,Lotus Europa,30.4,4,95.1,113.0,3.77,1.513,16.90,1,1,5.0,2.0
28,Ford Pantera L,15.8,8,351.0,264.0,4.22,3.170,14.50,0,1,5.0,4.0
29,Ferrari Dino,19.7,6,145.0,175.0,3.62,2.770,15.50,0,1,5.0,6.0
30,Maserati Bora,15.0,8,301.0,335.0,3.54,3.570,14.60,0,1,5.0,8.0
31,Volvo 142E,21.4,4,121.0,109.0,4.11,2.780,18.60,1,1,4.0,2.0

In [34]:
cars_new.fillna(method= 'ffill')

,Model,MPG,Cylinders,DISP,HP,D_Ratio,Weight,QSEC,VS,AM,Gear,Carb
0,Mazda RX4,21.0,6,160.0,110.0,3.90,2.620,16.46,0,1,4.0,4.0
1,Mazda RX4 Wag,21.0,6,160.0,110.0,3.90,2.875,17.02,0,1,4.0,4.0
2,Datsun 710,22.8,4,108.0,93.0,3.85,2.320,18.61,1,1,4.0,1.0
3,Hornet 4 Drive,21.4,6,258.0,110.0,3.08,3.215,19.44,1,0,3.0,1.0
4,Hornet Sportabout,18.7,8,360.0,175.0,3.15,3.440,17.02,0,0,3.0,2.0
5,Valiant,18.1,6,225.0,105.0,2.76,3.460,20.22,1,0,3.0,1.0
6,Duster 360,14.3,8,360.0,245.0,3.21,3.570,15.84,0,0,3.0,4.0
7,Merc 240D,24.4,4,146.7,62.0,3.69,3.190,20.00,1,0,4.0,2.0
8,Merc 230,22.8,4,140.8,95.0,3.92,3.150,22.90,1,0,4.0,2.0
9,Merc 280,19.2,6,167.6,123.0,3.92,3.440,18.30,1,0,4.0,4.0
10,Merc 280C,17.8,6,167.6,123.0,3.92,3.440,18.90,1,0,4.0,4.0
11,Merc 450SE,16.4,8,275.8,180.0,3.07,4.070,17.40,0,0,3.0,3.0
12,Merc 450SL,17.3,8,275.8,180.0,3.07,3.730,17.60,0,0,3.0,3.0
13,Merc 450SLC,15.2,8,275.8,180.0,3.07,3.780,18.00,0,0,3.0,3.0
14,Cadillac Fleetwood,10.4,8,472.0,205.0,2.93,5.250,17.98,0,0,3.0,4.0
15,Lincoln Continental,10.4,8,460.0,215.0,2.93,5.424,17.82,0,0,3.0,4.0
16,Chrysler Imperial,14.7,8,440.0,230.0,3.23,5.345,17.82,0,0,3.0,4.0
17,Fiat 128,32.4,4,78.7,66.0,4.08,2.200,19.47,1,1,4.0,1.0
18,Honda Civic,30.4,4,75.7,52.0,4.93,1.615,18.52,1,1,4.0,1.0
19,Toyota Corolla,33.9,4,71.1,65.0,4.22,1.835,19.90,1,1,4.0,1.0
20,Toyota Corona,21.5,4,120.1,97.0,3.70,2.465,20.01,1,0,3.0,1.0
21,Dodge Challenger,15.5,8,318.0,150.0,2.76,3.520,16.87,0,0,3.0,2.0
22,AMC Javelin,15.2,8,304.0,150.0,3.15,3.435,17.30,0,0,3.0,2.0
23,Camaro Z28,13.3,8,350.0,245.0,3.73,3.840,15.41,0,0,3.0,4.0
24,Pontiac Firebird,19.2,8,400.0,175.0,3.08,3.845,17.05,0,0,3.0,2.0
25,Fiat X1-9,27.3,4,79.0,66.0,4.08,1.935,18.90,1,1,4.0,1.0
26,Porsche 914-2,26.0,4,120.3,91.0,4.43,1.935,16.70,0,1,5.0,2.0
27,Lotus Europa,30.4,4,95.1,113.0,3.77,1.513,16.90,1,1,5.0,2.0
28,Ford Pantera L,15.8,8,351.0,264.0,4.22,3.170,14.50,0,1,5.0,4.0
29,Ferrari Dino,19.7,6,145.0,175.0,3.62,2.770,15.50,0,1,5.0,6.0
30,Maserati Bora,15.0,8,301.0,335.0,3.54,3.570,14.60,0,1,5.0,8.0
31,Volvo 142E,21.4,4,121.0,109.0,4.11,2.780,18.60,1,1,4.0,2.0

In [35]:
cars_new.fillna(method= 'bfill')

,Model,MPG,Cylinders,DISP,HP,D_Ratio,Weight,QSEC,VS,AM,Gear,Carb
0,Mazda RX4,21.0,6,160.0,110.0,3.90,2.620,16.46,0,1,4.0,4.0
1,Mazda RX4 Wag,21.0,6,160.0,110.0,3.90,2.875,17.02,0,1,4.0,4.0
2,Datsun 710,22.8,4,108.0,93.0,3.85,2.320,18.61,1,1,4.0,1.0
3,Hornet 4 Drive,21.4,6,258.0,110.0,3.08,3.215,19.44,1,0,3.0,1.0
4,Hornet Sportabout,18.7,8,360.0,175.0,3.15,3.440,17.02,0,0,3.0,2.0
5,Valiant,18.1,6,225.0,105.0,2.76,3.460,20.22,1,0,3.0,1.0
6,Duster 360,14.3,8,360.0,245.0,3.21,3.570,15.84,0,0,3.0,4.0
7,Merc 240D,24.4,4,146.7,62.0,3.69,3.190,20.00,1,0,4.0,2.0
8,Merc 230,22.8,4,140.8,95.0,3.92,3.150,22.90,1,0,4.0,2.0
9,Merc 280,19.2,6,167.6,123.0,3.92,3.440,18.30,1,0,4.0,4.0
10,Merc 280C,17.8,6,167.6,123.0,3.92,3.440,18.90,1,0,4.0,4.0
11,Merc 450SE,16.4,8,275.8,180.0,3.07,4.070,17.40,0,0,3.0,3.0
12,Merc 450SL,17.3,8,472.0,180.0,3.07,3.730,17.60,0,0,3.0,3.0
13,Merc 450SLC,15.2,8,472.0,180.0,3.07,3.780,18.00,0,0,3.0,3.0
14,Cadillac Fleetwood,10.4,8,472.0,205.0,2.93,5.250,17.98,0,0,3.0,4.0
15,Lincoln Continental,14.7,8,460.0,215.0,3.23,5.424,17.82,0,0,3.0,4.0
16,Chrysler Imperial,14.7,8,440.0,230.0,3.23,5.345,19.47,0,0,3.0,4.0
17,Fiat 128,32.4,4,78.7,66.0,4.08,2.200,19.47,1,1,4.0,1.0
18,Honda Civic,30.4,4,75.7,52.0,4.93,1.615,18.52,1,1,4.0,1.0
19,Toyota Corolla,33.9,4,71.1,65.0,4.22,1.835,19.90,1,1,4.0,1.0
20,Toyota Corona,21.5,4,120.1,97.0,3.70,2.465,20.01,1,0,3.0,1.0
21,Dodge Challenger,15.5,8,318.0,150.0,2.76,3.520,16.87,0,0,3.0,2.0
22,AMC Javelin,15.2,8,304.0,245.0,3.15,3.435,17.30,0,0,3.0,2.0
23,Camaro Z28,13.3,8,350.0,245.0,3.73,3.840,15.41,0,0,3.0,4.0
24,Pontiac Firebird,19.2,8,400.0,175.0,3.08,3.845,17.05,0,0,3.0,2.0
25,Fiat X1-9,27.3,4,79.0,66.0,4.08,1.935,18.90,1,1,4.0,1.0
26,Porsche 914-2,26.0,4,120.3,91.0,4.43,1.513,16.70,0,1,5.0,2.0
27,Lotus Europa,30.4,4,95.1,113.0,3.77,1.513,16.90,1,1,5.0,2.0
28,Ford Pantera L,15.8,8,351.0,264.0,4.22,3.170,14.50,0,1,5.0,4.0
29,Ferrari Dino,19.7,6,145.0,175.0,3.62,2.770,15.50,0,1,5.0,6.0
30,Maserati Bora,15.0,8,301.0,335.0,3.54,3.570,14.60,0,1,5.0,8.0
31,Volvo 142E,21.4,4,121.0,109.0,4.11,2.780,18.60,1,1,4.0,2.0

In [36]:
cars_new.groupby('Gear').mean()

,MPG,Cylinders,DISP,HP,D_Ratio,Weight,QSEC,VS,AM,Carb
Gear,,,,,,,,,,
3.0,16.984615,7.428571,322.575000,175.923077,3.158462,3.795643,17.690769,0.214286,0.000000,2.571429
4.0,24.533333,4.666667,123.016667,89.500000,4.043333,2.616667,18.965000,0.833333,0.666667,2.363636
5.0,21.380000,6.000000,202.480000,195.600000,3.916000,2.755750,15.640000,0.200000,1.000000,4.400000

In [37]:
cars_new.groupby('Gear').median()

       MPG  Cylinders   DISP     HP  D_Ratio  Weight    QSEC  VS  AM  Carb
Gear
3.0   16.4          8  334.0  180.0     3.08    3.65  17.400   0   0   2.5
4.0   22.8          4  130.9   94.0     3.92    2.70  18.755   1   1   2.0
5.0   19.7          6  145.0  175.0     3.77    2.97  15.500   0   1   4.0

In [38]:
cars_new.groupby('AM').median()

      MPG  Cylinders   DISP     HP  D_Ratio  Weight   QSEC  VS  Gear  Carb
AM
0   17.55          8  304.0  175.0     3.15    3.52  17.90   0   3.0   3.0
1   22.80          4  120.3  109.0     4.08    2.47  17.02   1   4.0   2.0

In [39]:
cars_new.groupby('Cylinders').mean()

,MPG,DISP,HP,D_Ratio,Weight,QSEC,VS,AM,Gear,Carb
Cylinders,,,,,,,,,,
4,26.663636,105.136364,82.636364,4.070909,2.300300,19.137273,0.909091,0.727273,4.090909,1.500000
6,19.742857,183.314286,122.285714,3.585714,3.117143,17.977143,0.571429,0.428571,3.857143,3.428571
8,15.461538,365.983333,213.769231,3.246923,3.999214,16.722308,0.000000,0.142857,3.307692,3.500000

In [41]:
cars_new.groupby('Cylinders').describe()

            MPG                                                      DISP  \
          count       mean       std   min    25%   50%   75%   max count
Cylinders
4          11.0  26.663636  4.509828  21.4  22.80  26.0  30.4  33.9  11.0
6           7.0  19.742857  1.453567  17.8  18.65  19.7  21.0  21.4   7.0
8          13.0  15.461538  2.262203  10.4  14.70  15.2  16.4  19.2  12.0

                       ... Gear       Carb                                 \
                 mean  ...  75%  max count      mean       std  min   25%
Cylinders              ...
4          105.136364  ...  4.0  5.0  10.0  1.500000  0.527046  1.0  1.00
6          183.314286  ...  4.0  5.0   7.0  3.428571  1.812654  1.0  2.50
8          365.983333  ...  3.0  5.0  14.0  3.500000  1.556624  2.0  2.25


           50%  75%  max
Cylinders
4          1.5  2.0  2.0
6          4.0  4.0  6.0
8          3.5  4.0  8.0

[3 rows x 80 columns]

In [44]:
cars_new["Cylinders"].unique()

array([6, 4, 8], dtype=int64)

In [45]:
cars_new["Cylinders"].value_counts()

8    14
4    11
6     7
Name: Cylinders, dtype: int64

In [46]:
cars_new["AM"].value_counts()

0    19
1    13
Name: AM, dtype: int64

In [47]:
cars_new["Gear"].value_counts()

3.0    14
4.0    12
5.0     5
Name: Gear, dtype: int64

In [48]:
cars_new["MPG"].value_counts()

15.2    2
21.0    2
19.2    2
30.4    2
22.8    2
21.4    2
16.4    1
21.5    1
27.3    1
15.0    1
10.4    1
26.0    1
15.5    1
19.7    1
32.4    1
15.8    1
18.7    1
13.3    1
18.1    1
33.9    1
14.3    1
14.7    1
24.4    1
17.8    1
17.3    1
Name: MPG, dtype: int64

In [49]:
cars_new["HP"].value_counts()

110.0    3
180.0    3
175.0    3
245.0    2
66.0     2
123.0    2
215.0    1
91.0     1
95.0     1
150.0    1
93.0     1
62.0     1
105.0    1
205.0    1
52.0     1
113.0    1
264.0    1
335.0    1
65.0     1
109.0    1
230.0    1
97.0     1
Name: HP, dtype: int64

In [50]:
cars_new["Gear"].nunique()

3

In [51]:
cars_new["AM"].nunique()

2

In [62]:
cars_new[(cars_new['HP']>=150) & (cars_new['AM']==1)]

,Model,MPG,Cylinders,DISP,HP,D_Ratio,Weight,QSEC,VS,AM,Gear,Carb
28,Ford Pantera L,15.8,8,351.0,264.0,4.22,3.17,14.5,0,1,5.0,4.0
29,Ferrari Dino,19.7,6,145.0,175.0,3.62,2.77,15.5,0,1,5.0,6.0
30,Maserati Bora,15.0,8,301.0,335.0,3.54,3.57,14.6,0,1,5.0,8.0

In [67]:
cars_new[(cars_new['HP']>=150) | (cars_new['AM']==1) | (cars_new["Gear"]>4)]

,Model,MPG,Cylinders,DISP,HP,D_Ratio,Weight,QSEC,VS,AM,Gear,Carb
0,Mazda RX4,21.0,6,160.0,110.0,3.90,2.620,16.46,0,1,4.0,4.0
1,Mazda RX4 Wag,21.0,6,160.0,110.0,3.90,2.875,17.02,0,1,4.0,4.0
2,Datsun 710,22.8,4,108.0,93.0,3.85,2.320,18.61,1,1,4.0,1.0
4,Hornet Sportabout,18.7,8,360.0,175.0,3.15,3.440,17.02,0,0,3.0,2.0
6,Duster 360,14.3,8,360.0,245.0,3.21,3.570,15.84,0,0,3.0,4.0
11,Merc 450SE,16.4,8,275.8,180.0,3.07,4.070,17.40,0,0,3.0,3.0
12,Merc 450SL,17.3,8,NaN,180.0,3.07,3.730,17.60,0,0,3.0,3.0
13,Merc 450SLC,15.2,8,NaN,180.0,3.07,3.780,18.00,0,0,3.0,3.0
14,Cadillac Fleetwood,10.4,8,472.0,205.0,2.93,5.250,17.98,0,0,NaN,4.0
15,Lincoln Continental,NaN,8,460.0,215.0,NaN,5.424,17.82,0,0,3.0,4.0
16,Chrysler Imperial,14.7,8,440.0,230.0,3.23,5.345,NaN,0,0,3.0,4.0
17,Fiat 128,32.4,4,78.7,66.0,4.08,2.200,19.47,1,1,4.0,1.0
18,Honda Civic,30.4,4,75.7,52.0,4.93,1.615,18.52,1,1,4.0,NaN
19,Toyota Corolla,33.9,4,71.1,65.0,4.22,1.835,19.90,1,1,4.0,1.0
21,Dodge Challenger,15.5,8,318.0,150.0,2.76,3.520,16.87,0,0,3.0,2.0
23,Camaro Z28,13.3,8,350.0,245.0,3.73,3.840,15.41,0,0,3.0,4.0
24,Pontiac Firebird,19.2,8,400.0,175.0,3.08,3.845,17.05,0,0,3.0,2.0
25,Fiat X1-9,27.3,4,79.0,66.0,4.08,1.935,18.90,1,1,4.0,1.0
26,Porsche 914-2,26.0,4,120.3,91.0,4.43,NaN,16.70,0,1,5.0,2.0
27,Lotus Europa,30.4,4,95.1,113.0,3.77,1.513,16.90,1,1,5.0,2.0
28,Ford Pantera L,15.8,8,351.0,264.0,4.22,3.170,14.50,0,1,5.0,4.0
29,Ferrari Dino,19.7,6,145.0,175.0,3.62,2.770,15.50,0,1,5.0,6.0
30,Maserati Bora,15.0,8,301.0,335.0,3.54,3.570,14.60,0,1,5.0,8.0
31,Volvo 142E,21.4,4,121.0,109.0,4.11,2.780,18.60,1,1,4.0,2.0

In [68]:
cars_new.columns

Index(['Model', 'MPG', 'Cylinders', 'DISP', 'HP', 'D_Ratio', 'Weight', 'QSEC',
       'VS', 'AM', 'Gear', 'Carb'],
      dtype='object')

In [73]:
new_col = [1,2,3,4,5,6,7,8,9,10,11,12]

In [74]:
cars_new.columns = new_col

In [75]:
cars_new

,1,2,3,4,5,6,7,8,9,10,11,12
0,Mazda RX4,21.0,6,160.0,110.0,3.90,2.620,16.46,0,1,4.0,4.0
1,Mazda RX4 Wag,21.0,6,160.0,110.0,3.90,2.875,17.02,0,1,4.0,4.0
2,Datsun 710,22.8,4,108.0,93.0,3.85,2.320,18.61,1,1,4.0,1.0
3,Hornet 4 Drive,21.4,6,258.0,110.0,3.08,3.215,19.44,1,0,3.0,1.0
4,Hornet Sportabout,18.7,8,360.0,175.0,3.15,3.440,17.02,0,0,3.0,2.0
5,Valiant,18.1,6,225.0,105.0,2.76,3.460,20.22,1,0,3.0,1.0
6,Duster 360,14.3,8,360.0,245.0,3.21,3.570,15.84,0,0,3.0,4.0
7,Merc 240D,24.4,4,146.7,62.0,3.69,3.190,20.00,1,0,4.0,2.0
8,Merc 230,22.8,4,140.8,95.0,3.92,3.150,22.90,1,0,4.0,2.0
9,Merc 280,19.2,6,167.6,123.0,3.92,3.440,18.30,1,0,4.0,4.0
10,Merc 280C,17.8,6,167.6,123.0,3.92,3.440,18.90,1,0,4.0,4.0
11,Merc 450SE,16.4,8,275.8,180.0,3.07,4.070,17.40,0,0,3.0,3.0
12,Merc 450SL,17.3,8,NaN,180.0,3.07,3.730,17.60,0,0,3.0,3.0
13,Merc 450SLC,15.2,8,NaN,180.0,3.07,3.780,18.00,0,0,3.0,3.0
14,Cadillac Fleetwood,10.4,8,472.0,205.0,2.93,5.250,17.98,0,0,NaN,4.0
15,Lincoln Continental,NaN,8,460.0,215.0,NaN,5.424,17.82,0,0,3.0,4.0
16,Chrysler Imperial,14.7,8,440.0,230.0,3.23,5.345,NaN,0,0,3.0,4.0
17,Fiat 128,32.4,4,78.7,66.0,4.08,2.200,19.47,1,1,4.0,1.0
18,Honda Civic,30.4,4,75.7,52.0,4.93,1.615,18.52,1,1,4.0,NaN
19,Toyota Corolla,33.9,4,71.1,65.0,4.22,1.835,19.90,1,1,4.0,1.0
20,Toyota Corona,21.5,4,120.1,97.0,3.70,2.465,20.01,1,0,3.0,1.0
21,Dodge Challenger,15.5,8,318.0,150.0,2.76,3.520,16.87,0,0,3.0,2.0
22,AMC Javelin,15.2,8,304.0,NaN,3.15,3.435,17.30,0,0,3.0,2.0
23,Camaro Z28,13.3,8,350.0,245.0,3.73,3.840,15.41,0,0,3.0,4.0
24,Pontiac Firebird,19.2,8,400.0,175.0,3.08,3.845,17.05,0,0,3.0,2.0
25,Fiat X1-9,27.3,4,79.0,66.0,4.08,1.935,18.90,1,1,4.0,1.0
26,Porsche 914-2,26.0,4,120.3,91.0,4.43,NaN,16.70,0,1,5.0,2.0
27,Lotus Europa,30.4,4,95.1,113.0,3.77,1.513,16.90,1,1,5.0,2.0
28,Ford Pantera L,15.8,8,351.0,264.0,4.22,3.170,14.50,0,1,5.0,4.0
29,Ferrari Dino,19.7,6,145.0,175.0,3.62,2.770,15.50,0,1,5.0,6.0
30,Maserati Bora,15.0,8,301.0,335.0,3.54,3.570,14.60,0,1,5.0,8.0
31,Volvo 142E,21.4,4,121.0,109.0,4.11,2.780,18.60,1,1,4.0,2.0

In [72]:
new_col

['Model',
 'mpg',
 'Cyl',
 'disp',
 'hp',
 'D_Ratio',
 'Weight',
 'qsec',
 'VS',
 'AM',
 'Gear',
 'Carb']

In [79]:
cars_evl = pd.read_csv('C:\\Users\\sunil\\Desktop\\car_evaluation.csv',header=None)

In [80]:
cars_evl.head()

       0      1  2  3      4     5      6
0  vhigh  vhigh  2  2  small   low  unacc
1  vhigh  vhigh  2  2  small   med  unacc
2  vhigh  vhigh  2  2  small  high  unacc
3  vhigh  vhigh  2  2    med   low  unacc
4  vhigh  vhigh  2  2    med   med  unacc

In [81]:
student={"name":["ram sekhar","sandeep sai","sai kumar"],"age":[22,33,55]}

In [82]:
student

{'name': ['ram sekhar', 'sandeep sai', 'sai kumar'], 'age': [22, 33, 55]}

In [87]:
Std_data = pd.DataFrame(student)

In [88]:
Std_data

          name  age
0   ram sekhar   22
1  sandeep sai   33
2    sai kumar   55

In [93]:
Std_data['name'].str.split()

0     [ram, sekhar]
1    [sandeep, sai]
2      [sai, kumar]
Name: name, dtype: object

In [92]:
Std_data['name'].str.split(expand=True)

         0       1
0      ram  sekhar
1  sandeep     sai
2      sai   kumar

In [94]:
Std_data[['F_name','L_name']] = Std_data['name'].str.split(expand=True)

In [95]:
Std_data

          name  age   F_name  L_name
0   ram sekhar   22      ram  sekhar
1  sandeep sai   33  sandeep     sai
2    sai kumar   55      sai   kumar

In [103]:
Std_data.drop('name', axis=1,inplace=True)

In [104]:
Std_data

   age   F_name  L_name
0   22      ram  sekhar
1   33  sandeep     sai
2   55      sai   kumar